# Generated by Django 5.0.1 on 2024-03-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movel',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
