# Generated by Django 5.0.1 on 2024-03-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0002_alter_movel_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaavulsa',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
