# Generated by Django 5.0.1 on 2024-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0003_pecaavulsa_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecaavulsa',
            name='valor_metro_quadrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
