# Generated by Django 5.0.1 on 2024-03-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0005_pecaavulsa_movel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pecaavulsa',
            name='valor_metro_quadrado',
        ),
        migrations.AddField(
            model_name='pecaavulsa',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bode.material'),
            preserve_default=False,
        ),
    ]
