# Generated by Django 5.0.1 on 2024-03-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0006_material_remove_pecaavulsa_valor_metro_quadrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.CharField(default='Cliente', max_length=255),
        ),
    ]
