# Generated by Django 5.0.1 on 2024-03-31 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bode', '0008_rename_movels_orcamento_moveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='moveis',
        ),
        migrations.AddField(
            model_name='movel',
            name='orcamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bode.orcamento'),
            preserve_default=False,
        ),
    ]
